name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1.0.1
      with:
        aws-access-key-id: AKIAJSIE27KKMHXI3BJQ
        aws-secret-access-key: 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
        aws-region: eu-central-1
    - name: Validate with pre-commit
      run: |
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files
    - name: Test with unittest
      run: |
        python -m unittest discover -v lambdas/tests
