name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Validate with pre-commit
      run: |
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files
    - name: Test with unittest
      uses: aws-actions/configure-aws-credentials@v1.0.1
      with:
        aws-region: eu-central-1
      run: |
        python -m unittest discover -v lambdas/tests
